data "digitalocean_droplet" "forgejo" {
  name = "forgejo-node"
}
module "forgejo" {
  source          = "../../forgejo"
  ADMIN_USERNAME  = var.ADMIN_USERNAME
  ADMIN_PASSWORD  = var.ADMIN_PASSWORD
  ADMIN_EMAIL     = var.ADMIN_EMAIL
  KUBECONFIG_PATH = "../kubeconfig"

  ROOT_DOMAIN = var.ROOT_DOMAIN
  SUB_DOMAIN  = var.SUB_DOMAIN

  DIGITALOCEAN_TOKEN             = var.DIGITALOCEAN_TOKEN
  DIGITALOCEAN_SPACES_ACCESS_ID  = var.DIGITALOCEAN_SPACES_ACCESS_ID
  DIGITALOCEAN_SPACES_SECRET_KEY = var.DIGITALOCEAN_SPACES_SECRET_KEY

  FORGEJO_BUCKET_ENDPOINT          = var.FORGEJO_BUCKET_ENDPOINT
  FORGEJO_BUCKET_ACCESS_ID         = var.FORGEJO_BUCKET_ACCESS_ID
  FORGEJO_BUCKET_SECRET_ACCESS_KEY = var.FORGEJO_BUCKET_SECRET_ACCESS_KEY
  FORGEJO_BUCKET_NAME              = var.FORGEJO_BUCKET_NAME
  FORGEJO_BUCKET_REGION            = var.FORGEJO_BUCKET_REGION

  DB_BACKUP_BUCKET = "test"
  INSTANCE_IP      = data.digitalocean_droplet.forgejo.ipv4_address
}
